// packages/website/docs/.vitepress/theme/components/Hero/Hero.vue
<script setup lang="ts">
import CTAButton from "@theme/components/Buttons/CTAButton.vue";
// import WCEmbed from '@theme/components/Examples/WCEmbed/WCEmbed.vue';
import BlockNote from "@theme/components/Examples/BlockNote/BlockNote.vue";
</script>

<template>
  <header>
    <div class="header-content">
      <h1>
        The open source <strong>Block-Based</strong><br />rich text editor
      </h1>
      <p>
        A beautiful text editor that just works. Easily add an editor to your
        app that users will love. Customize it with your own functionality like
        custom blocks or AI tooling.
      </p>
      <div class="cta-buttons">
        <CTAButton href="/docs/quickstart">Get started (beta)</CTAButton>
        <!-- <CTAButton href="/guides/introduction" layout="simple"
          >Learn more</CTAButton
        > -->
      </div>
    </div>

    <div class="header-media">
      <div class="editor-wrapper">
        <ClientOnly><BlockNote /></ClientOnly>
      </div>
      <div class="try-here-image" />
    </div>
    <!-- features
sponsors
contributors / community
prosemirror / tiptap

React or Vanilla -->
  </header>
</template>

<style scoped lang="scss">
@import "@theme/styles/vars";

header {
  position: relative;
  display: flex;
  gap: 84px;
  width: var(--content-max-width);
  max-width: 100%;
  margin: 0 auto 52px;
  padding: 0 52px;
  @media (max-width: 1280px) {
    gap: 64px;
    padding-right: 32px;
  }
  @media (max-width: 1024px) {
    flex-direction: column;
    align-items: center;
  }
  @media (max-width: 500px) {
    padding: 0 12px;
  }
}

.header-content {
  flex: 1.2;
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: flex-start;
  gap: 32px;
  @media (max-width: 1024px) {
    align-items: center;
  }
}

.header-media {
  display: flex;
  flex-direction: column;
  transform: translateY(-80px);
  max-width: 596px;
  width: 100%;
  @media (max-width: 1460px) {
    width: 44%;
  }
  @media (max-width: 1280px) {
    width: 48%;
  }
  @media (max-width: 1024px) {
    width: 100%;
    transform: translateY(0);
  }

  @media only screen and (hover: none) and (pointer: coarse) {
    display: none; /* disable on mobile */
  }
}

.editor-wrapper {
  border-radius: 12px;
  box-shadow: inset 0 0 0 1px #c4d0d966, inset 0 -1px #ffffff1a,
    inset 0 1px #84b9f61a;
  // background-image: radial-gradient(
  //   145% 110% at 46% 20%,
  //   #fdfeff 50%,
  //   #f0f5fa 85%,
  //   #9abfe1 100%
  // );
  background: white;
  backdrop-filter: blur(6px);
  padding: 50px;
  padding-left: 1px;
  overflow-y: scroll;
}

html.dark .editor-wrapper {
  background: #111418;
}

.try-here-image {
  position: relative;
  width: 250px;
  height: 160px;
  right: 120px;
  display: block;
  top: -50px;

  background-image: url(/img/assets/try.svg);
  :root.dark & {
    background-image: url(/img/assets/try.dark.svg);
  }
  background-size: contain;
  background-repeat: no-repeat;

  @media (max-width: 1280px) {
    right: 0;
  }
}

$icon-mask: linear-gradient(to bottom, #fff9 10%, #fffa 30%, #fff0 74%);

header .icon {
  width: 160px;
  height: 160px;
  color: var(--sb-foreground-highlight);
  -webkit-mask-image: $icon-mask;
  mask-image: $icon-mask;

  @media (prefers-contrast: more) {
    display: none;
  }

  @media (min-width: $bp-medium) {
    width: 200px;
    height: 200px;
  }
}

header h1 {
  margin-bottom: 0;
  font-family: Gilroy, var(--vp-font-family-base);
  line-height: 1.2;
  font-weight: 400;
  margin-top: -25px;
  font-size: 76px;
  letter-spacing: -2px;
  line-height: 1;
  color: #000;
  :root.dark & {
    color: #fff;
  }

  strong {
    font-weight: 600;
  }

  @media (max-width: 1400px) {
    font-size: 68px;
  }
  @media (max-width: 1280px) {
    font-size: 60px;
  }
  @media (max-width: 1024px) {
    text-align: center;
  }
  @media (max-width: 960px) {
    margin-top: -15px;
    font-size: 40px;
  }
}

header p {
  max-width: 600px;
  margin: 0.75em 0 1.5em;
  font-size: 18px;
  font-weight: 500;
  line-height: 1.6;
  @media (max-width: 1280px) {
    font-size: 16px;
  }
  @media (max-width: 1024px) {
    margin-bottom: 12px;
    text-align: center;
  }
  @media (max-width: 960px) {
    font-size: 16px;
  }
}

.cta-buttons {
  display: flex;
  gap: 16px;
  width: 100%;
  @media (max-width: 1024px) {
    justify-content: center;
  }
}
</style>

// docs/components/pages/landing/hero/Hero.tsx
// import { PackLogo } from "../../logos/PackLogo";

import dynamic from "next/dynamic";
import Image from "next/image";
import { HeroText, SectionSubtext } from "../../home-shared/Headings";
import { FadeIn } from "../shared/FadeIn";

import { useTheme } from "nextra-theme-docs";
import tryHereImageDark from "../../../../public/img/assets/try.dark.svg";
import tryHereImageLight from "../../../../public/img/assets/try.svg";
import Link from "next/link";

const Demo = dynamic(() => import("@/components/pages/landing/hero/Demo"), {
  ssr: false,
});

export function Hero() {
  const { theme } = useTheme();
  return (
    <section className="relative flex h-fit w-full items-center justify-center overflow-hidden py-36">
      <div className="z-20 flex w-screen max-w-full flex-col items-center justify-between gap-16 px-6 md:max-w-screen-md xl:max-w-[1440px] xl:flex-row">
        <FadeIn className="flex h-fit flex-col items-center justify-center gap-5 text-center xl:w-[584px] xl:items-start xl:text-left">
          <HeroText h1>
            The open source
            <br />
            <strong>Block-Based</strong>
            <br />
            rich text editor
          </HeroText>
          <SectionSubtext>
            A beautiful text editor that just works. Easily add an editor to
            your app that users will love. Customize it with your own
            functionality like custom blocks or AI tooling.
          </SectionSubtext>
          <div className="button-glow-parent relative flex h-fit w-fit flex-wrap gap-x-6 gap-y-4">
            <Link
              className={
                "z-20 rounded-full bg-slate-800 px-4 py-2 text-lg font-medium text-white"
              }
              href="/docs">
              Get Started
            </Link>
            <div
              className={"button-glow absolute z-10 h-full w-full rounded-full"}
            />
          </div>
        </FadeIn>
        <div className="relative h-[36rem] w-full shrink-0 grow-0 rounded-lg xl:w-[584px]">
          <FadeIn noVertical className={"absolute z-10 h-full w-full"}>
            <div className={"editor-glow h-full w-full"} />
          </FadeIn>
          <div className="relative z-20 h-full w-full overflow-scroll overscroll-contain rounded-lg">
            {/* TODO: Wait for editor & collab content to load before rendering. Show placeholder or delay loading?*/}
            <Demo theme={theme === "dark" ? "dark" : "light"} />
            {/* <BackgroundIllustration className="absolute left-1/2 top-4 h-[1026px] w-[1026px] -translate-x-1/3 stroke-gray-300/70 [mask-image:linear-gradient(to_bottom,white_20%,transparent_75%)] sm:top-16 sm:-translate-x-1/2 lg:-top-16 lg:ml-12 xl:-top-14 xl:ml-0" />
        <div className="-mx-4 h-[448px] px-9 [mask-image:linear-gradient(to_bottom,white_60%,transparent)] sm:mx-0 lg:absolute lg:-inset-x-10 lg:-bottom-20 lg:-top-10 lg:h-auto lg:px-0 lg:pt-10 xl:-bottom-32">
          <PhoneFrame className="mx-auto max-w-[366px]" priority>
            <AppDemo />
          </PhoneFrame>
        </div> */}
          </div>
          <Image
            src={tryHereImageLight}
            className={
              "relative bottom-24 left-10 z-30 float-right block size-56 dark:hidden"
            }
            alt="Try it out"
          />
          <Image
            src={tryHereImageDark}
            className={
              "relative bottom-24 left-10 z-30 float-right hidden size-56 dark:block"
            }
            alt="Try it out"
          />
        </div>
        {/* <div className="relative -mt-4 lg:col-span-7 lg:mt-0 xl:col-span-6">
            <p className="text-center text-sm font-semibold text-gray-900 lg:text-left">
              As featured in
            </p>
          </div> */}
      </div>
    </section>
  );
}

//     /*
// return (
//   <FadeIn
//     className="font-sans w-auto min-h-[calc(100svh-var(--nextra-navbar-height))] pb-16 pt-[48px] md:pb-24 lg:pb-32 md:pt-16 lg:pt-20 flex justify-between gap-8 items-center flex-col relative z-0"
//     noVertical>
//     <FadeIn className="z-50 flex items-center justify-center w-full">
//       <div className="w-[120px] z-50 mt-[-8.075px] mb-[-8.075px]"></div>
//     </FadeIn>
//     {/* <Gradient
//       className="top-[-500px] dark:opacity-20 opacity-[0.15]"
//       conic
//       height={1000}
//       width={1000}
//     /> */}
//     <div
//       className={classNames(
//         "absolute top-0 z-10 w-full h-48 dark:from-black from-white to-transparent bg-gradient-to-b",
//         styles.contentContainer
//       )}
//     />
//     <FadeIn
//       className={classNames(
//         "z-50 flex flex-col gap-5 px-6 text-left lg:gap-6 ",
//         styles.contentContainer
//       )}
//       delay={0.15}>
//       {/* <PackLogo
//         alt="Turbopack"
//         className="w-[160px] md:w-[200px] fill-black dark:fill-white"
//         width="200"
//       /> */}
//       <div className="flex flex-col">
//         <HeroText h1>
//           The open source <strong>Block-Based</strong>
//           <br />
//           rich text editor
//         </HeroText>
//         <SectionSubtext hero>
//           A beautiful text editor that just works. Easily add an editor to
//           your app that users will love. Customize it with your own
//           functionality like custom blocks or AI tooling.
//         </SectionSubtext>
//       </div>
//     </FadeIn>
//     <FadeIn
//       className="z-50 flex flex-col items-center w-full max-w-md gap-5 px-6"
//       delay={0.3}>
//       <div className="flex flex-col w-full gap-3 md:!flex-row">
//         <CTAButton>
//           <Link className="block py-3" href="/docs">
//             Get Started
//           </Link>
//         </CTAButton>
//       </div>
//     </FadeIn>
//     <FadeIn className="relative w-full" delay={0.5}>
//       <div className="absolute bottom-0 w-full dark:from-black from-white to-transparent h-72 bg-gradient-to-t" />
//     </FadeIn>
//   </FadeIn>
// );*/
// }
